#!/bin/sh
mkdir $1
SCRIPT_DIR=$(cd $(dirname $0); pwd)
cp $SCRIPT_DIR/template.html $1/index.html
cp $SCRIPT_DIR/index_body_template.html $1/index_body_.html
cp $SCRIPT_DIR/update_index $1/update_index
sed -i "" "s/FILE_NAME/index_body/g" $1/index.html
sed -i "" "s/TITLE/$2/g" $1/index.html
sed -i "" "s/TITLE/$2/g" $1/index_body_.html
$1/update_index
$SCRIPT_DIR/cates_update